import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import clsx from "clsx";
import StarIcon from "@material-ui/icons/Star";
import StarBorderIcon from "@material-ui/icons/StarBorder";
import StarHalfIcon from "@material-ui/icons/StarHalf";
import CurrencyFormat from "react-currency-format";
import Layout from "../components/layout/Layout";
import MiniGallery from "../components/mini-gallery/MiniGallery";
import SimpleCard from "../components/cards/SimpleCard";
import CustomSelect from "../components/custom-inputs/CustomSelect";
import CustomTextInput from "../components/custom-inputs/CustomTextInput";
import { featuredProducts, renderProductDesc } from "../constants";
import styles from "../styles/Cart.module.css";

export default function Cart() {
  //   const [state, setState] = useState({ size: null, quantity: 1 });
  //   const [bigImage, setBigImage] = useState(product?.images[0]);

  //   const handleChange = (e) => {
  //     if (e.value) {
  //       return setState((prevVal) => ({
  //         ...prevVal,
  //         size: e,
  //       }));
  //     }
  //     const { name, value } = e.target;
  //     return setState((prevVal) => ({
  //       ...prevVal,
  //       [name]: value,
  //     }));
  //   };

  return (
    <div>
      <Layout>
        <Head>
          <title>FitStop | Product_details</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <div className={clsx("container", styles.cart_page)}>
          <table className={styles.cart_table}>
            <tr>
              <th>Product</th>
              <th>Quantity</th>
              <th>Subtotal</th>
            </tr>
            <tr>
              <td>
                <div className={styles.cart_info}>
                  <div className={styles.product_img}>
                  <Image
                    src="/images/gallery-1.jpg"
                    alt="card image"
                    width={80}
                    height={80}
                  />
                  </div>
                  <div>
                    <p>Red Printed T-Shirt</p>
                    <CurrencyFormat
                      renderText={(value) => (
                        <div className="price_box">
                          <small className="smallroduct__price">
                            Price: {value}
                          </small>
                        </div>
                      )}
                      decimalScale={2}
                      value={9000}
                      displayType={"text"}
                      thousandSeparator={true}
                      prefix="₦"
                    />
                    <a className={styles.remove_btn}>Remove</a>
                  </div>
                </div>
              </td>
              <td>
                <div className={styles.input}>
                  <CustomTextInput
                    //   label="quantity"
                    name="quantity"
                    // value={state?.quantity}
                    // onChange={handleChange}
                    componentProps={{ type: "number", min: 1 }}
                  />
                </div>
              </td>
              <td>
                <CurrencyFormat
                  renderText={(value) => (
                    <div className="price_box">
                      <p className="product__price">{value}</p>
                    </div>
                  )}
                  decimalScale={2}
                  value={9000}
                  displayType={"text"}
                  thousandSeparator={true}
                  prefix="₦"
                />
              </td>
            </tr>
          </table>
          <div className={styles.total_price}>
            <table>
              <tr>
                <td>Subtotal</td>
                <td>
                  <CurrencyFormat
                    renderText={(value) => (
                      <div className="price_box">
                        <p className="product__price">{value}</p>
                      </div>
                    )}
                    decimalScale={2}
                    value={9000}
                    displayType={"text"}
                    thousandSeparator={true}
                    prefix="₦"
                  />
                </td>
              </tr>
              <tr>
                <td>Tax</td>
                <td>
                  <CurrencyFormat
                    renderText={(value) => (
                      <div className="price_box">
                        <p className="product__price">{value}</p>
                      </div>
                    )}
                    decimalScale={2}
                    value={500}
                    displayType={"text"}
                    thousandSeparator={true}
                    prefix="₦"
                  />
                </td>
              </tr>
              <tr>
                <td>Total</td>
                <td>
                  <CurrencyFormat
                    renderText={(value) => (
                      <div className="price_box">
                        <p className="product__price">{value}</p>
                      </div>
                    )}
                    decimalScale={2}
                    value={9500}
                    displayType={"text"}
                    thousandSeparator={true}
                    prefix="₦"
                  />
                </td>
              </tr>
            </table>
          </div>
        </div>
      </Layout>
    </div>
  );
}
