import React, { useState } from "react";
import Head from "next/head";
import clsx from "clsx";
import Layout from "../components/layout/Layout";
import MiniGallery from "../components/mini-gallery/MiniGallery";
import SimpleCard from "../components/cards/SimpleCard";
import CustomSelect from "../components/custom-inputs/CustomSelect";
import { featuredProducts, renderProductDesc } from "../constants";
import styles from "../styles/Products.module.css";

const sortList = [
  { value: "none", label: "none" },
  { value: "price", label: "sort by price" },
  { value: "popularity", label: "sort by popularity" },
  { value: "rating", label: "sort by rating" },
  { value: "sale", label: "sort by sale" },
];

export default function Products() {
  const [sort, setSort] = useState(null);
  return (
    <Layout>
      <Head>
        <title>FitStop | Products</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container">
        <div className={clsx("row", styles.filter_row)}>
          <h2>All Products</h2>
          <CustomSelect
            name="sortBy"
            value={sort}
            options={sortList}
            onChange={setSort}
            componentProps={{ isSearchable: false, placeholder: "sort by" }}
          />
        </div>
        <MiniGallery classes={styles.gallery}>
          {featuredProducts.map((item, index) => (
            <SimpleCard
              classes="shdw pad_1 card_3d"
              key={index}
              size={4}
              image={item.image}
              renderContent={() => renderProductDesc(item)}
            />
          ))}
        </MiniGallery>
        <div className={styles.page_btn}>
            <span>1</span>
            <span>2</span>
            <span>3</span>
            <span>4</span>
            <span>&#8594;</span>
        </div>
      </div>
    </Layout>
  );
}
